// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: code.proto

package code

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeService_ExplainCode_FullMethodName = "/code.CodeService/ExplainCode"
)

// CodeServiceClient is the client API for CodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeServiceClient interface {
	ExplainCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CodeResponse], error)
}

type codeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeServiceClient(cc grpc.ClientConnInterface) CodeServiceClient {
	return &codeServiceClient{cc}
}

func (c *codeServiceClient) ExplainCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CodeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CodeService_ServiceDesc.Streams[0], CodeService_ExplainCode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CodeRequest, CodeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeService_ExplainCodeClient = grpc.ServerStreamingClient[CodeResponse]

// CodeServiceServer is the server API for CodeService service.
// All implementations must embed UnimplementedCodeServiceServer
// for forward compatibility.
type CodeServiceServer interface {
	ExplainCode(*CodeRequest, grpc.ServerStreamingServer[CodeResponse]) error
	mustEmbedUnimplementedCodeServiceServer()
}

// UnimplementedCodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeServiceServer struct{}

func (UnimplementedCodeServiceServer) ExplainCode(*CodeRequest, grpc.ServerStreamingServer[CodeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExplainCode not implemented")
}
func (UnimplementedCodeServiceServer) mustEmbedUnimplementedCodeServiceServer() {}
func (UnimplementedCodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeCodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeServiceServer will
// result in compilation errors.
type UnsafeCodeServiceServer interface {
	mustEmbedUnimplementedCodeServiceServer()
}

func RegisterCodeServiceServer(s grpc.ServiceRegistrar, srv CodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedCodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeService_ServiceDesc, srv)
}

func _CodeService_ExplainCode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CodeServiceServer).ExplainCode(m, &grpc.GenericServerStream[CodeRequest, CodeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeService_ExplainCodeServer = grpc.ServerStreamingServer[CodeResponse]

// CodeService_ServiceDesc is the grpc.ServiceDesc for CodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "code.CodeService",
	HandlerType: (*CodeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExplainCode",
			Handler:       _CodeService_ExplainCode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "code.proto",
}
