// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: article.proto

package article

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleService_GetArticleInfoFirst_FullMethodName = "/article.articleService/GetArticleInfoFirst"
	ArticleService_SaveArticleID_FullMethodName       = "/article.articleService/SaveArticleID"
	ArticleService_GetArticleInfo_FullMethodName      = "/article.articleService/GetArticleInfo"
	ArticleService_DelArticleInfo_FullMethodName      = "/article.articleService/DelArticleInfo"
)

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleServiceClient interface {
	// 第一次获取文章的摘要、总结、标签
	GetArticleInfoFirst(ctx context.Context, in *GetArticleInfoFirstRequest, opts ...grpc.CallOption) (*GetArticleInfoFirstResponse, error)
	// 将文章的ID保存到相应的记录中
	SaveArticleID(ctx context.Context, in *SaveArticleIDRequest, opts ...grpc.CallOption) (*SaveArticleIDResponse, error)
	// 非首次获取文章的摘要、总结、标签
	GetArticleInfo(ctx context.Context, in *GetArticleInfoRequest, opts ...grpc.CallOption) (*GetArticleInfoResponse, error)
	// 删除文章相关信息
	DelArticleInfo(ctx context.Context, in *DelArticleInfoRequest, opts ...grpc.CallOption) (*DelArticleInfoResponse, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) GetArticleInfoFirst(ctx context.Context, in *GetArticleInfoFirstRequest, opts ...grpc.CallOption) (*GetArticleInfoFirstResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleInfoFirstResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetArticleInfoFirst_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) SaveArticleID(ctx context.Context, in *SaveArticleIDRequest, opts ...grpc.CallOption) (*SaveArticleIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveArticleIDResponse)
	err := c.cc.Invoke(ctx, ArticleService_SaveArticleID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetArticleInfo(ctx context.Context, in *GetArticleInfoRequest, opts ...grpc.CallOption) (*GetArticleInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleInfoResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetArticleInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) DelArticleInfo(ctx context.Context, in *DelArticleInfoRequest, opts ...grpc.CallOption) (*DelArticleInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelArticleInfoResponse)
	err := c.cc.Invoke(ctx, ArticleService_DelArticleInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations must embed UnimplementedArticleServiceServer
// for forward compatibility.
type ArticleServiceServer interface {
	// 第一次获取文章的摘要、总结、标签
	GetArticleInfoFirst(context.Context, *GetArticleInfoFirstRequest) (*GetArticleInfoFirstResponse, error)
	// 将文章的ID保存到相应的记录中
	SaveArticleID(context.Context, *SaveArticleIDRequest) (*SaveArticleIDResponse, error)
	// 非首次获取文章的摘要、总结、标签
	GetArticleInfo(context.Context, *GetArticleInfoRequest) (*GetArticleInfoResponse, error)
	// 删除文章相关信息
	DelArticleInfo(context.Context, *DelArticleInfoRequest) (*DelArticleInfoResponse, error)
	mustEmbedUnimplementedArticleServiceServer()
}

// UnimplementedArticleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleServiceServer struct{}

func (UnimplementedArticleServiceServer) GetArticleInfoFirst(context.Context, *GetArticleInfoFirstRequest) (*GetArticleInfoFirstResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleInfoFirst not implemented")
}
func (UnimplementedArticleServiceServer) SaveArticleID(context.Context, *SaveArticleIDRequest) (*SaveArticleIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveArticleID not implemented")
}
func (UnimplementedArticleServiceServer) GetArticleInfo(context.Context, *GetArticleInfoRequest) (*GetArticleInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleInfo not implemented")
}
func (UnimplementedArticleServiceServer) DelArticleInfo(context.Context, *DelArticleInfoRequest) (*DelArticleInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelArticleInfo not implemented")
}
func (UnimplementedArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {}
func (UnimplementedArticleServiceServer) testEmbeddedByValue()                        {}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	// If the following call pancis, it indicates UnimplementedArticleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_GetArticleInfoFirst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleInfoFirstRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleInfoFirst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticleInfoFirst_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleInfoFirst(ctx, req.(*GetArticleInfoFirstRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_SaveArticleID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveArticleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).SaveArticleID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_SaveArticleID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).SaveArticleID(ctx, req.(*SaveArticleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetArticleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleInfo(ctx, req.(*GetArticleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_DelArticleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelArticleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).DelArticleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_DelArticleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).DelArticleInfo(ctx, req.(*DelArticleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "article.articleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticleInfoFirst",
			Handler:    _ArticleService_GetArticleInfoFirst_Handler,
		},
		{
			MethodName: "SaveArticleID",
			Handler:    _ArticleService_SaveArticleID_Handler,
		},
		{
			MethodName: "GetArticleInfo",
			Handler:    _ArticleService_GetArticleInfo_Handler,
		},
		{
			MethodName: "DelArticleInfo",
			Handler:    _ArticleService_DelArticleInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}
