database:
  host: "192.168.10.4"
  port: 3310
  user: "root"
  password: "123456"
  name: "forum"

# redis 暂时未使用--

redis:
  host: "192.168.10.4"
  port: 6379
  password: "123456"
  db: 0

app:
  host: "0.0.0.0"
  port: 8081

# 发送邮件
send_email:
  From : "3174285493@qq.com"
  host: "smtp.qq.com"
  port: 587
  username: "3174285493@qq.com"
  authorizeCode: "mmureuzrdnmndfef"

# 静态资源存储
static:
  prefix: "/images"
  path: "./static/images"

# 日志配置
log:
  #  level: "debug"
  logPath: "./logs"
  appName: "forum"