database:
  host: "192.168.10.4"
  port: 3306
  user: "root"
  password: "123456"
  name: "forum"

# redis 暂时未使用--

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

app:
  host: "0.0.0.0"
  port: 8081

# 发送验证码
verifyCode:
  From : "3174285493@qq.com"
  Subject: "验证码"
  VerifyCodeLen: 6
  VerifyCodeEffectiveDuration: 100
  VerifyCodeCoolTime: 1
  host: "smtp.qq.com"
  port: 587
  username: "3174285493@qq.com"
  authorizeCode: "mmureuzrdnmndfef"

