database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456987"
  name: "forum"

# redis 暂时未使用

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

app:
  host: "0.0.0.0"
  port: 8081