#database:
#  host: "8.154.36.180"
#  port: 8901
#  user: "siwu"
#  password: "siwu@2025"
#  name: "siwu"
#
#redis:
#  host: "8.154.36.180"
#  port: 8902
#  password: "lezhiedu@2024"
#  db: 5
#
#  pool_size: 10            # 连接池大小，默认为 10
#  min_idle_conns: 3        # 最小空闲连接数，默认为 3
#  dial_timeout: 5s        # 连接超时时间
#  read_timeout: 30s       # 读取超时时间
#  write_timeout: 30s      # 写入超时时间
#  idle_timeout: 300s      # 连接最大空闲时间，默认为 5分钟（300秒）
#  max_retries: 3         # 最大重试次数
#
##app:
##  host: "192.168.10.7"
##  port: 8081
#
## 发送邮件
#send_email:
#  From: "3174285493@qq.com"
#  host: "smtp.qq.com"
#  port: 587
#  username: "3174285493@qq.com"
#  authorizeCode: "mmureuzrdnmndfef"
#
## 静态资源存储
#static:
#  prefix: "/images"
#  path: "./static/images"
#
## 日志配置
#log:
#  #  level: "debug"
#  logPath: "./logs"
#  appName: "forum"

database:
  host: "shuXueMysql"
  port: 3306
  user: "siwu"
  password: "siwu@2025"
  name: "siwu"

redis:
  host: "shuXueRedis"
  port: 6379
  password: "lezhiedu@2024"
  db: 5

  pool_size: 10            # 连接池大小，默认为 10
  min_idle_conns: 3        # 最小空闲连接数，默认为 3
  dial_timeout: 5s        # 连接超时时间
  read_timeout: 30s       # 读取超时时间
  write_timeout: 30s      # 写入超时时间
  idle_timeout: 300s      # 连接最大空闲时间，默认为 5分钟（300秒）
  max_retries: 3         # 最大重试次数

app:
  host: ""
  port: 8110
  domain: "8.154.36.180" # 域名

# 发送邮件
send_email:
  From: "3174285493@qq.com"
  host: "smtp.qq.com"
  port: 587
  username: "3174285493@qq.com"
  authorizeCode: "mmureuzrdnmndfef"

# 静态资源存储
static:
  prefix: "/images"
  path: "./static/images"
  limit: 2                    # 上传图片文件的大小限制，单位是MB, 数值类型为int64
  watermark: "思悟"            # 图片水印的内容
  size: 36                    # 水印的大小
  scale: 1.5                 # 图片压缩时的缩放比例（用于文章比例的限制）
  margin: 10.0                # 水印距离左下角的距离 ，规则: 从右向左移动margin个位置的距离，从下往上移动3*margin个位置的距离
  user_default_image: "995e61bd-9182-4e12-8a6f-c6b8c3883044.png"  #不用加前缀 比如: http://8.154.36.180:8110/images/ 直接填文件名和文件扩展即可
  article_default_image: "8cfc551a-1f33-43df-8b3f-024e44213666.jpeg"
  tag_default_image: "b4e001d7-99ca-49f5-a218-f02f305cb042.jpeg"
  advertisement_default_image: ""
  comment_default_image: ""
  category_default_image: ""

# 日志配置
log:
  #  level: "debug"
  logPath: "./logs"
  appName: "forum"

etcd:
  endpoints: "8.154.36.180:2379" # etcd 服务端地址